### PR TITLE
Various CMake cleanups

### PR DESCRIPTION
**Pull request by ishitatsuyuki**
Come on, this is 2016, not 2006.

You still think people can live with software which is 5-years old?

### CODE REVIEW

**Comment by jbeder** [comment]
This is a bunch of changes in one. Some, I assume, are uncontroversial, like cleaning up the cmake variables. Others are more difficult, like bumping the cmake version. Note that 3.0 came out in June 2014. I don't have a great sense of how widespread it is, but check out, e.g., issue #361 for a request to preserve 2.6 instead of 2.8.

**Comment by ishitatsuyuki** [comment]
Note that you are planning to use c++11. It's safe to deprecate 2.6 since it's 2008. Do you think 2008 compilers handles c++11?

I used your neighbor, jsoncpp, as a reference. They are using 2.8. I think 3.0 is old enough(over 1 year) though.

**Comment by jbeder** [comment]
cmake 2.8 came out in Nov 2009. I think based on this argument (using C++11), it's fine to require 2.8. Let's give 3.0 a little more time, though.

**Comment by ishitatsuyuki** [comment]
That looks the best solution. Will remove the 3.0 changes tomorrow.

**Comment by paulnovo** [comment]
@ishitatsuyuki Using yaml-cpp from its build directory now doesn't work. Well, it half works, an external project will find yaml-cpp in its build directory, but the include directories are wrong. You deleted the code to handle this, and instead are creating yaml-cpp-config.cmake twice.

**Comment by ishitatsuyuki** [comment]
@paulnovo using a library from build directory is a BAD practice. It should be only hacked locally and never published.

BTW, can you comment on the code that generates twice?

**Comment by paulnovo** [comment]
@ishitatsuyuki I think using yaml-cpp from the build directory was the behavior of yaml-cpp even before PR #344, so this would be a change for some people. It is also part of CMake's own tutorials on how to install cmake files:

https://cmake.org/Wiki/CMake/Tutorials/How_to_create_a_ProjectConfig.cmake_file

If you believe using the library from the build directory is bad practice, find_package(yaml-cpp) should not find yaml-cpp in the build directory. Which it still does with these changes, and when it finds yaml-cpp, the include directories are incorrect.

Lines 247 and 252 appear to both generate yaml-cpp-config.cmake. Where before, these lines used to generate one for the build directory and one to be installed.

**Comment by ishitatsuyuki** [comment]
Uploaded new patch set.

**Comment by tambry** [comment]
@ishitatsuyuki Are you planning to still work on this? It's currently conflicting and needs to be rebased.

**Comment by ishitatsuyuki** [comment]
I hope someone to adopt it; I'm no longer using this library due to various design flaws (like #370).

**Comment by tambry** [comment]
@ishitatsuyuki What library are you using instead? I'm not sure if I'd consider #370 a design flaw, since copying a node and then modifying the copied node shouldn't modify the original node, because it was copied over.

**Comment by ishitatsuyuki** [comment]
@tambry I simply don't use YAML anymore; also, a "Node" is a reference-like object in yaml-cpp, #370 is about the inconsistent behavior between an empty node and data-filled one.

**Comment by tambry** [comment]
Thank you! Might consider making my own YAML C++ library once I get time, as this doesn't seem to be very actively maintained, although it's quite an OK library on the API side.

**Comment by mwoehlke-kitware** [comment]
What changes here are still wanted? (In particular, is bumping minimum CMake to 2.8.11 / 2.8.12 in order to guarantee target usage requirements are available acceptable?) I might be willing to take over some of this effort.

**Comment by jbeder** [comment]
CMake 2.8 sounds fine to me. I have no particular desires about the CMake files, so if you can suggest some changes that have value, I'm happy to pull them.

**Comment by ishitatsuyuki** [comment]
I'm closing this as I no longer work on this. I would suggest submitting an up-to-date patch set based on this. To sum up, bumping the CMake requirement is fine (for 2.8), but some cleanup affects in-tree library linkage, which is a breaking change.

**Comment by mwoehlke-kitware** [comment]
Does it seem okay to require CMake ≥ 2.8.12? IIUC, the concern was with RHEL. EPEL for 6.8 contains CMake 2.8.12 (and also some flavor of CMake 3.x).

2.8.12 is new enough to ensure good support for target usage requirements, which in particular allows use of stuff like [`target_include_directories`](https://cmake.org/cmake/help/v3.0/command/target_include_directories.html) ([ugly 2.8.12 doc](https://cmake.org/cmake/help/v2.8.12/cmake.html#command:target_include_directories)), as has been discussed here.

**Comment by jbeder** [comment]
Sure, 2.8.12 is fine.

**Pull request closed without merging**
