### PR TITLE
set CMAKE_POSITION_INDEPENDENT_CODE if BUILD_SHARED_LIBS=OFF

### PR DESCRIPTION
**Pull request by christian-rauch**

### CODE REVIEW

**Comment by gelldur** [comment]
This will set PIC for all targets (what if someone adds library as `sub-directory`, maybe set_property would be better?
```set_property(TARGET lib1 PROPERTY POSITION_INDEPENDENT_CODE ON)```

**Comment by christian-rauch** [comment]
If `BUILD_SHARED_LIBS=OFF` then every library, that hasn't explicitly set `SHARED` or `STATIC` will build as `STATIC`. I think that PIC should therefore apply to all static libraries that the cmake project builds.

**Comment by milipili** [comment]
Property on targets should be used instead. It is not rare that CMake projects are included into another, and deciding to set `CMAKE_POSITION_INDEPENDENT_CODE` will just break everything.

It should always be per target. Also why setting position indepdendant code if building a static library? In many cases we dont want that option. Only if it is included into a bigger shared library

**Comment by christian-rauch** [comment]
> In many cases we dont want that option.

Why? You will need that option if you want to link your static library into an executable.

**Comment by christian-rauch** [comment]
> Property on targets should be used instead.

I set this for the target `yaml-cpp` only. I think this is the only target in the project.

**Review by jbeder — APPROVED** [review]

**Comment by jbeder** [comment]
Fixes #1031

**Pull request merged**
