### PR TITLE
fix: revert ABI breakage

### PR DESCRIPTION
**Pull request by liujianqiang-niu**
add patch to revert abi breakage.

Log:

### CODE REVIEW

**Comment by liujianqiang-niu** [comment]
> 

The symbol _ZN4YAML6detail9node_data12empty_scalarB5cxx11E (YAML::detail::node_data::empty_scalar[abi:cxx11]) is no longer provided by /lib64/libyaml-cpp.so.0.7.

**Comment by jbeder** [comment]
It looks like this is from #559. But your PR passes the windows/shared tests. Do you have any idea why the original PR felt like they needed to change it?

**Comment by shenlebantongying** [comment]
This damage was already done, downstream already fixed this breakage in some way (like recompiling the chain of dependency). If you revert or release again, they have to do it all over again. Please evaluate if they have to redo everything before reverting!

This bug might be an expected behaviour now.

There are more, but here are some examples:



```
https://stackoverflow.com/questions/52713571/mongod-symbol-lookup-error-mongod-undefined-symbol-zn4yaml6detail9node-data
[https://forums.opensuse.org/showthread.php/538693-Blender-failed-to-launch-after-update-symbol-lookup-error-undefine-symbol 1](https://forums.opensuse.org/showthread.php/538693-Blender-failed-to-launch-after-update-symbol-lookup-error-undefine-symbol)
https://bugzilla.opensuse.org/show_bug.cgi?id=1160171
https://bugzilla.redhat.com/show_bug.cgi?id=1773357
https://bugzilla.redhat.com/show_bug.cgi?id=1774164
https://bbs.archlinux.org/viewtopic.php?id=248014
https://github.com/jbeder/yaml-cpp/issues/484
```

**Comment by shenlebantongying** [comment]
IIRC It happened between 0.6.2 -> 0.6.3.

A minor version bump -> The `libc.so.6` name didn't change -> distros assume ABI didn't change -> breakages.

Some distro maybe considers 0.6->0.7 is also a minor change, thus we got this pull request to revert it.

(I cannot confirm but it seems to recompile can just solve the problem.)

**Comment by jbeder** [comment]
OK, sounds good, I'll close this PR.

**Pull request closed without merging**
