### PR TITLE
Upgrade embedded version of gmock+gtest to 1.8.0

### PR DESCRIPTION
**Pull request by rleigh-codelibre**
See also: https://github.com/jbeder/yaml-cpp/issues/493

This commit upgrades gmock and gtest to 1.8.0, fixing the segfault noted in the issue.  It very much looks like gmock 1.7.0 is broken, and this defect is exposed when using reasonably contemporary compilers (both GCC and Clang).  Not bleeding edge; just those used in the latest stable releases of FreeBSD and Ubuntu, and doubtless others as well.

### CODE REVIEW

**Comment by jbeder** [comment]
Looks like it fails on clang? Maybe worth splitting these up into to PRs so that they don't get squashed, in any case.

**Comment by rleigh-codelibre** [comment]
Yes, I can split them apart.  The clang error is because Travis is using clang 3.4 with the *GCC 4.6* headers, and it's hitting some brokenness in those libstdc++ headers.  These are not a particularly great combination, and I'm not sure how realistic this scenario is for real-world usage.

I'm investigating if there's a way to work around this, but it may well be the case that the Travis test setup is broken for these type_trait templates.  There's no bug in either the yaml-cpp or googletest code that I can see.

**Comment by rleigh-codelibre** [comment]
As a data point, on FreeBSD 10.3 with clang++ 3.4.1, this builds and tests perfectly.  It's definitely the unholy combination of clang++ with libstdc++ that's at fault here.

**Comment by rleigh-codelibre** [comment]
The last commit is a total cheat, which drops the linux/clang combination from the matrix.  From what I can tell, and what's been reported, it's not a particularly viable setup.  Looks like people who want to test this are configuring travis to use their own docker images which are set up with a working compiler and standard library combination.  At work, we use FreeBSD for this purpose (this PR works perfectly there), but the MacOS X axis of the matrix is already providing good coverage here.

**Comment by keith-bennett-gbg** [comment]
Also seems to resolve https://github.com/jbeder/yaml-cpp/issues/478

**Comment by rleigh-codelibre** [comment]
For the clang with buggy libstdc++ issue, see also:

- https://groups.google.com/forum/#!topic/travis-ci/YvZuAVBNYMw
- http://www.itgo.me/a/x2917008569641495753/travis-ci-with-clang-3-4-and-c11/30925448
- http://redmine.gromacs.org/issues/1886

If you liked, I could look at using a more recent libstdc++ with travis?

**Comment by rleigh-codelibre** [comment]
@jbeder Did you want any further changes making on this PR?

**Comment by jbeder** [comment]
@rleigh-codelibre Sounds good. I'll merge this, but can you file an issue about that linux/clang issue, referencing this PR, and the links you've found? Not that we need to do any action on that right now, but just so we surface it.

**Comment by rleigh-codelibre** [comment]
@jbeder Hope the above issue and cross-references are OK.

**Pull request merged**
