### PR TITLE
Add the AppVeyor configuration file.

### PR DESCRIPTION
**Pull request by dota17**
Add the AppVeyor configuration file. The final effect is shwon in [demo](https://github.com/dota17/yaml-cpp/pull/38)

### CODE REVIEW

**Comment by jbeder** [comment]
Looks like there's a segfault in the tests? Do you know why?

**Comment by dota17** [comment]
Yes, this segfault error has been fixed in PR #926.

**Comment by jbeder** [comment]
Ah yes. Can you sync and rerun the tests?

**Comment by dota17** [comment]
Ok, done.

**Pull request merged**
